apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-dynamic
  namespace: ams-database
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path